import { podcastEpisodeSchema } from "@/lib/content/schemas";
import type { PodcastEpisode } from "@/lib/content/types";

const records = [
  { slug: "when-gods-will-doesnt-go-your-way", title: "When God's Will doesn't go your way", description: "A conversation about patience, persistence, and trusting God when a faithful path still includes defeat or delay.", publishedAt: "2025-07-18T21:09:39Z", durationSeconds: 2222, audioUrl: "https://mcdn.podbean.com/mf/web/ps6vkqm3eernmuw8/EP7_PODCAST_AUDIOanwkp.mp3", pageUrl: "https://thelioncompany.podbean.com/e/when-gods-will-doesnt-go-your-way/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/The_Lion_Company_Podcast_Thumbnail_q7z96q.jpg", episodeNumber: 7, transcriptUrl: null },
  { slug: "confessions-of-a-truth-teller-the-dark-side-of-being-light", title: "Confessions of a Truth Teller: The Dark side of Being Light", description: "Jonathan and Gina consider why honesty can hurt and heal, and how to speak truth in love from marriage to ministry.", publishedAt: "2025-05-20T01:45:03Z", durationSeconds: 3752, audioUrl: "https://mcdn.podbean.com/mf/web/hqr9yuje96suuy82/EP_66qyz9.mp3", pageUrl: "https://thelioncompany.podbean.com/e/confessions-of-a-truth-teller-the-dark-side-of-being-light/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/ep_6_fixed9pih4.jpg", episodeNumber: 6, transcriptUrl: null },
  { slug: "miracle-or-madness", title: "Miracle or Madness?", description: "A personal conversation about forgiveness, supernatural encounters, painful histories, and the possibilities of genuine faith.", publishedAt: "2025-01-25T07:19:46Z", durationSeconds: 5462, audioUrl: "https://mcdn.podbean.com/mf/web/fxviqxtf46n875c6/Lion_Company_Podcast_EP_59338t.mp3", pageUrl: "https://thelioncompany.podbean.com/e/miracle-or-madness/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/Image_1-24-25_at_949_PM_4ka4eb.jpg", episodeNumber: 5, transcriptUrl: null },
  { slug: "the-dark-side-of-emotional-intelligence-and-how-to-fix-it", title: "The Dark Side of Emotional Intelligence (and How to fix it)", description: "Jonathan and Natalie discuss over-giving, discernment, boundaries, leadership, and relationships.", publishedAt: "2025-01-11T06:01:00Z", durationSeconds: null, audioUrl: "https://mcdn.podbean.com/mf/web/eers7fsdu2aypfhm/The_Lion_Company_Podcast_Episode_4bjew3.mp3", pageUrl: "https://thelioncompany.podbean.com/e/the-dark-side-of-emotional-intelligence-and-how-to-fix-it/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/Untitled-2_1__7jk4tv.png", episodeNumber: 4, transcriptUrl: null },
  { slug: "trapped-by-fear-and-stuck-in-the-past", title: "Trapped by Fear and Stuck in the Past? How One Prophetic Word Changed Everything", description: "Gina and Natalie share a story about fear, people-pleasing, obedience, hope, and stepping into a life of purpose.", publishedAt: "2025-01-03T21:30:11Z", durationSeconds: null, audioUrl: "https://mcdn.podbean.com/mf/web/g59wpw6n4cvexyu5/Lion_Co_EP369ch7.mp3", pageUrl: "https://thelioncompany.podbean.com/e/trapped-by-fear-and-stuck-in-the-past-how-one-prophetic-word-changed-everything/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/Untitled_2__883v4f.png", episodeNumber: 3, transcriptUrl: null },
  { slug: "authenticity-endurance-and-the-call-to-the-bride", title: "Authenticity, Endurance, and the Call to the Bride – A Candid Conversation with Andrew Billings | Part 1", description: "Jonathan Gibson and Andrew Billings discuss authenticity in ministry, endurance through hardship, and relational discipleship.", publishedAt: "2024-12-18T20:03:51Z", durationSeconds: null, audioUrl: "https://mcdn.podbean.com/mf/web/u6mcuqe7mh6niajw/The_Lion_Company_PODCAST_Billing_pt_18juvm.mp3", pageUrl: "https://thelioncompany.podbean.com/e/authenticity-endurance-and-the-call-to-the-bride-%e2%80%93-a-candid-conversation-with-andrew-billings-part-1/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/Lion_Co_Podcast_EP_2_IG_SQ_hfn8sv.png", episodeNumber: 2, transcriptUrl: null },
  { slug: "overcoming-the-past-redefining-success-and-finding-gods-purpose", title: "Overcoming the Past, Redefining Success, and Finding God’s Purpose", description: "The opening episode explores past pain, inherited ideas of success, faith, and a renewed sense of purpose.", publishedAt: "2024-12-03T23:27:15Z", durationSeconds: 8612, audioUrl: "https://mcdn.podbean.com/mf/web/sczpt4dbrkuczepn/THE_LION_COMPANY_PODCAST_EP_1aqvqb.mp3", pageUrl: "https://thelioncompany.podbean.com/e/ep1/", imageUrl: "https://pbcdn1.podbean.com/imglogo/ep-logo/pbblog16332481/Untitled-2.jpeg", episodeNumber: 1, transcriptUrl: null },
] as const;

export const podcastFallback: readonly PodcastEpisode[] = records.map((record) => podcastEpisodeSchema.parse(record));
